[phases.setup]
nixPkgs = ["ffmpeg", "python310Full", "gcc", "stdenv.cc.cc.lib"]

[phases.install]
cmds = [
    "python3.10 -m ensurepip --upgrade",
    "python3.10 -m pip install --upgrade pip",
    "python3.10 -m pip install -r requirements.txt"
]

[start]
cmd = "cd backend && python3.10 api_server.py"
